### ISSUE TITLE
Firefox publishing new extension instead of new version

### ISSUE THREAD

**Issue by ianwremmel** [LinusU/wext-shipit#13]
Am I missing a value somewhere? What value does shipit use to uniquely identify AMO extensions? Instead of uploading a new version of my extension, shipit is creating a completely new extension.

**Comment by LinusU** [comment]
Do you have `applications.gecko.id` set in your manifest file?

Here you can see a working project that uses wext-shipit, we have been using it for every release:

https://github.com/ctrl-alt-deseat/ctrlpanel-extension

**Comment by ianwremmel** [comment]
Ah, got it. Thanks! Any chance of putting this in the README?

**Comment by LinusU** [comment]
Done 👍

**Comment by ianwremmel** [comment]
Thanks!
